twinkle_tag: 0.0.1

server:
  hostname: "shiny.dide.ic.ac.uk"
  email: "r.fitzjohn@imperial.ac.uk"
  port_http: 80
  port_https: 443
  # used for the self-signed certificate
  country: UK
  state: London
  organisation: DIDE

vault:
  address: "https://vault.dide.ic.ac.uk:8200"
  root: "/secret/shiny.dide"

apps:
  typochallenge:
    type: github
    spec: mrc-ide/typochallenge@auto_provision
    protect:
      paths:
        - emails.db
        - contributions

  eppasmviewer:
    type: github
    spec: mrc-ide/eppasmviewer/inst/shiny/eppasmviewer@auto_provision
    auth:
      type: deploy_key
    groups:
      - dide-internal

  debug:
    type: local
    spec: debug
    groups:
      - admin

  hello:
    type: local
    spec: hello

  test:
    type: local
    spec: test

groups:
  dide-internal:
    - rich
    - jeff
  admin:
    - admin
